### ISSUE TITLE
Fix Readme :)

### ISSUE THREAD

**Issue by sweetpi** [Fjuxx/pimatic-milight#1]

**Comment by mwittig** [comment]
HI @Fjuxx I am happy to help with README and other stuff. Just let me know if you are happy with this.

Btw, I have just tested you plugin which works fine! Excellent!

**Comment by Fjuxx** [comment]
Damn, you guys are fast ;) 
i just published it to see how this worked on my own pi.

But i think it is now done for a first release :) i will post it in the forums, with a nice place to buy them cheap :D
@mwittig There is a new update, it solves a few problems with rules, and it didnt memorize the dim level.

**Comment by mwittig** [comment]
OK, great! Looking forward to your post. I bought mine for 62 EUR - Remote Control, WiFi-Controller, 3 Lamps 6W plus 3 EUR postage. 

Btw, I have tested this using the Host IP address assigned to the Controller (no multicast). So, I guess multiple controllers should not be a problem then.

**Comment by Fjuxx** [comment]
There you go.

i just bought another set. wifi controller and 2 lamps for 36 EUR
